### ISSUE TITLE
Add language switcher drop-down menu to home page

### ISSUE THREAD

**Issue by ghjensen** [etcluvic/hsscommons#190]
If possible, we'd like to add the language switcher drop-down menu to the home page. Currently, the drop-down menu to select your preferred language only appears on pages other than the home page, even though it looks like the language switcher module is set to show up on all pages.

Is this because the breadcrumbs menu doesn't appear on the home page (and that's usually where the language menu is placed)?

**Comment by kgosal03** [comment]
Hi @ghjensen ! I was able to add the language switcher thing to the homepage. Do you want this text or should I delete this?
<img width="587" alt="image" src="https://github.com/etcluvic/hsscommons/assets/45154385/c8507aa8-7a8d-4a6e-a5d1-b000bf31fb68">

**Comment by kgosal03** [comment]
This is what is live on the test-commons now. Let me know if this is good otherwise I can revert the changes. 
<img width="920" alt="image" src="https://github.com/etcluvic/hsscommons/assets/45154385/bd72ab84-738a-4871-8022-2d71c9c731b0">

I have removed the text which I think what we want as the subhead was hidden before.

**Comment by ghjensen** [comment]
This looks great! I prefer it without the text (as in the most recent live version). Thanks, Karan. I'll merge this into h2.2.22 for our next update, at which point I will close this thread.

**Comment by kgosal03** [comment]
Sounds good!
