### ISSUE TITLE
Improve display of Featured Groups

### ISSUE THREAD

**Issue by ghjensen** [etcluvic/hsscommons#28]
On https://hsscommons.ca/groups, the icons for any "Featured Groups" are overly large, and the grey bar with text that appears below the icons extends the entire width of the screen. Ideally, we could shrink the entire containing element to a size that matches the group items listed above, and the grey bar with text (and optional "Join" button) would be scaled down accordingly. We could also set breakpoints so that the layout is responsive and multiple featured groups could appear side by side, adjusting dynamically according to the size of the browser window. (Perhaps if we set the featured groups section on this page to be responsive, we should also do the same for the "Popular Groups" section above it?)

Note: you can only mark a group as featured via the admin interface. Currently we've only featured two groups (but the screenshot below only features one).

<img width="1897" alt="Screen Shot 2023-02-03 at 9 47 58 AM" src="https://user-images.githubusercontent.com/12787016/216674476-283d3d3b-6570-4dda-bf3c-d9c6dab421f9.png">

**Comment by toanhminh0412** [comment]
The display of the featured groups should be fixed if merge pull request #30 into `test`.
Regarding setting the breakpoints so that multiple groups can appear side by side, the popular groups already look pretty good to me on the main website.
![image](https://user-images.githubusercontent.com/55383509/218184240-c9ed0bdd-1647-42c9-8c78-f63041079a2c.png)

I'm not 100% sure how to improve from this. Please give me some guidance

**Comment by ghjensen** [comment]
Ah, you're right--I hadn't noticed or had forgotten that there are already breakpoints for the popular groups section. you can ignore that part of my original comment!
